<?php
/**
 * AlbumType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Dinas\ShippingSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shipping API
 *
 * PHP client for Shipping API
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: info@dinas.jp
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Dinas\ShippingSdk\Model;
use \Dinas\ShippingSdk\ObjectSerializer;

/**
 * AlbumType Class Doc Comment
 *
 * @category Class
 * @description Photo album name. **default: yard_note**
 * @package  Dinas\ShippingSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AlbumType
{
    /**
     * Possible values of this enum
     */
    public const AUCTION = 'auction';

    public const YARD_NOTE = 'yard_note';

    public const YARD_CARGO = 'yard_cargo';

    public const YARD_PROBLEMS = 'yard_problems';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::AUCTION,
            self::YARD_NOTE,
            self::YARD_CARGO,
            self::YARD_PROBLEMS
        ];
    }
}


