<?php
/**
 * DocumentType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Dinas\ShippingSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shipping API
 *
 * PHP client for Shipping API
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: info@dinas.jp
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Dinas\ShippingSdk\Model;
use \Dinas\ShippingSdk\ObjectSerializer;

/**
 * DocumentType Class Doc Comment
 *
 * @category Class
 * @description Document type
 * @package  Dinas\ShippingSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DocumentType
{
    /**
     * Possible values of this enum
     */
    public const EXPORT_CERTIFICATE = 'export_certificate';

    public const VEHICLE_INVOICE = 'vehicle_invoice';

    public const VEHICLE_CATALOG = 'vehicle_catalog';

    public const PRICE_CONFIRMATION = 'price_confirmation';

    public const EXPLANATORY_NOTE = 'explanatory_note';

    public const REPAIR_ESTIMATE = 'repair_estimate';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::EXPORT_CERTIFICATE,
            self::VEHICLE_INVOICE,
            self::VEHICLE_CATALOG,
            self::PRICE_CONFIRMATION,
            self::EXPLANATORY_NOTE,
            self::REPAIR_ESTIMATE
        ];
    }
}


