<?php
/**
 * FuelType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Dinas\ShippingClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shipping API
 *
 * PHP client for Shipping API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@dinas.jp
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Dinas\ShippingClient\Model;
use \Dinas\ShippingClient\ObjectSerializer;

/**
 * FuelType Class Doc Comment
 *
 * @category Class
 * @package  Dinas\ShippingClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FuelType
{
    /**
     * Possible values of this enum
     */
    public const G = 'G';

    public const D = 'D';

    public const HV = 'HV';

    public const EV = 'EV';

    public const CNG = 'CNG';

    public const FCV = 'FCV';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::G,
            self::D,
            self::HV,
            self::EV,
            self::CNG,
            self::FCV
        ];
    }
}


