<?php
/**
 * StockStatus
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Dinas\ShippingClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shipping API
 *
 * PHP client for Shipping API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@dinas.jp
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Dinas\ShippingClient\Model;
use \Dinas\ShippingClient\ObjectSerializer;

/**
 * StockStatus Class Doc Comment
 *
 * @category Class
 * @package  Dinas\ShippingClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class StockStatus
{
    /**
     * Possible values of this enum
     */
    public const PENDING = 'pending';

    public const READY = 'ready';

    public const SHIPPED = 'shipped';

    public const DISCHARGED = 'discharged';

    public const RECEIVED = 'received';

    public const CANCELED = 'canceled';

    public const LOST = 'lost';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PENDING,
            self::READY,
            self::SHIPPED,
            self::DISCHARGED,
            self::RECEIVED,
            self::CANCELED,
            self::LOST
        ];
    }
}


