<?php
/**
 * VehicleType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Dinas\ShippingSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shipping API
 *
 * PHP client for Shipping API
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: info@dinas.jp
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Dinas\ShippingSdk\Model;
use \Dinas\ShippingSdk\ObjectSerializer;

/**
 * VehicleType Class Doc Comment
 *
 * @category Class
 * @package  Dinas\ShippingSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class VehicleType
{
    /**
     * Possible values of this enum
     */
    public const STATION_WAGON = 'station wagon';

    public const SEDAN = 'sedan';

    public const VAN = 'van';

    public const PICKUP = 'pickup';

    public const KEI_CAR = 'kei car';

    public const BUS = 'bus';

    public const TRUCK = 'truck';

    public const BIKE = 'bike';

    public const ATV = 'atv';

    public const SPECIAL_EQUIPMENT = 'special equipment';

    public const EXCAVATOR = 'excavator';

    public const TRACTOR = 'tractor';

    public const ROLLER = 'roller';

    public const CRANE = 'crane';

    public const FORKLIFT = 'forklift';

    public const BOAT = 'boat';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::STATION_WAGON,
            self::SEDAN,
            self::VAN,
            self::PICKUP,
            self::KEI_CAR,
            self::BUS,
            self::TRUCK,
            self::BIKE,
            self::ATV,
            self::SPECIAL_EQUIPMENT,
            self::EXCAVATOR,
            self::TRACTOR,
            self::ROLLER,
            self::CRANE,
            self::FORKLIFT,
            self::BOAT
        ];
    }
}


