<?php
/**
 * VoyageStatus
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Dinas\ShippingSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shipping API
 *
 * PHP client for Shipping API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@dinas.jp
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Dinas\ShippingSdk\Model;
use \Dinas\ShippingSdk\ObjectSerializer;

/**
 * VoyageStatus Class Doc Comment
 *
 * @category Class
 * @package  Dinas\ShippingSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class VoyageStatus
{
    /**
     * Possible values of this enum
     */
    public const PENDING = 'pending';

    public const LOADED = 'loaded';

    public const DEPARTED = 'departed';

    public const ARRIVED = 'arrived';

    public const CANCELED = 'canceled';

    public const LOST = 'lost';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PENDING,
            self::LOADED,
            self::DEPARTED,
            self::ARRIVED,
            self::CANCELED,
            self::LOST
        ];
    }
}


