<?php
/**
 * CarDocumentsTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Dinas\ShippingSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shipping API
 *
 * PHP client for Shipping API
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: info@dinas.jp
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Dinas\ShippingSdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CarDocumentsTest Class Doc Comment
 *
 * @category    Class
 * @description Documents attached to the car
 * @package     Dinas\ShippingSdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CarDocumentsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CarDocuments"
     */
    public function testCarDocuments()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "export_certificate"
     */
    public function testPropertyExportCertificate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "vehicle_invoice"
     */
    public function testPropertyVehicleInvoice()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "vehicle_catalog"
     */
    public function testPropertyVehicleCatalog()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "price_confirmation"
     */
    public function testPropertyPriceConfirmation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "explanatory_note"
     */
    public function testPropertyExplanatoryNote()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "repair_estimate"
     */
    public function testPropertyRepairEstimate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
