<?php
/**
 * CarsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Dinas\ShippingSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shipping API
 *
 * PHP client for Shipping API
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: info@dinas.jp
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Dinas\ShippingSdk\Test\Api;

use \Dinas\ShippingSdk\Configuration;
use \Dinas\ShippingSdk\ApiException;
use \Dinas\ShippingSdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CarsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Dinas\ShippingSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CarsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getCars
     *
     * Get paginated list of cars.
     *
     */
    public function testGetCars()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for grantCars
     *
     * Clear withhold status.
     *
     */
    public function testGrantCars()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for holdCars
     *
     * Hold cars from shipping.
     *
     */
    public function testHoldCars()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for releaseCars
     *
     * Allow us to ship cars.
     *
     */
    public function testReleaseCars()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for setYardEta
     *
     * Set yard ETA for cars.
     *
     */
    public function testSetYardEta()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for syncCars
     *
     * Create or update cars.
     *
     */
    public function testSyncCars()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for withholdCars
     *
     * Withhold cars upon arrival.
     *
     */
    public function testWithholdCars()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
